import gensim

# Retrieving the model
model = gensim.models.Word2Vec.load("ITWAC_model.csv")

# Finding the top 50 similarities for the colours
print("nero : ", model.wv.most_similar("nero", topn=50))
print()
print("nera : ", model.wv.most_similar("nera", topn=50))
print()
print("neri : ", model.wv.most_similar("neri", topn=50))
print()
print("nere : ", model.wv.most_similar("nere", topn=50))
print()
print("bianco : ", model.wv.most_similar("bianco", topn=50))
print()
print("bianca : ", model.wv.most_similar("bianca", topn=50))
print()
print("bianchi : ", model.wv.most_similar("bianchi", topn=50))
print()
print("bianche : ", model.wv.most_similar("bianche", topn=50))
print()
print("rosso : ", model.wv.most_similar("rosso", topn=50))
print()
print("rossa : ", model.wv.most_similar("rossa", topn=50))
print()
print("rossi : ", model.wv.most_similar("rossi", topn=50))
print()
print("rosse : ", model.wv.most_similar("rosse", topn=50))
print()
print("verde : ", model.wv.most_similar("verde", topn=50))
print()
print("verdi : ", model.wv.most_similar("verdi", topn=50))
print()
print("giallo : ", model.wv.most_similar("giallo", topn=50))
print()
print("gialla : ", model.wv.most_similar("gialla", topn=50))
print()
print("gialle : ", model.wv.most_similar("gialle", topn=50))
print()
print("gialli : ", model.wv.most_similar("gialli", topn=50))
print()
print("blu : ", model.wv.most_similar("blu", topn=50))
print()
print("marrone : ", model.wv.most_similar("marrone", topn=50))
print()
print("marroni : ", model.wv.most_similar("marroni", topn=50))
print()
print("arancione : ", model.wv.most_similar("arancione", topn=50))
print()
print("rosa : ", model.wv.most_similar("rosa", topn=50))
print()
print("viola : ", model.wv.most_similar("viola", topn=50))
print()
print("grigio : ", model.wv.most_similar("grigio", topn=50))
print()
print("grigia : ", model.wv.most_similar("grigia", topn=50))
print()
print("grigi : ", model.wv.most_similar("grigi", topn=50))
print()
print("grigie : ", model.wv.most_similar("grigie", topn=50))
print()